name = "youtube-rss-embed-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "YOUTUBE_FEED_CACHE"
id = "65fa36dc5e734defa3036a0b339ab762"
preview_id = "73a37d4c56fd42c1be955e7fb2fe173a"
